# user variables, change this to make custom site.

name: MoviesPLay 9
desc: Yet another simple theme for Jekyll.
author:
  name: MoviesPLay 9
  avatar: https://lh3.googleusercontent.com/--PTn2MpIZ5w/AAAAAAAAAAI/AAAAAAAAAAA/APJypA2_h9yREP4A2sEy5Zf3iyDnEkmR7Q/s300-p-rw-no-mo/photo.jpg
  profile: |
    Just another ordinary grad student in computer engineering.
    I'm interest in programming language, algorithm, and mathematics.

    I live in Chiang Mai or Bangkok, Thailand.
    And you may found me around BarCamp event ;D
  socials:
    facebook: //facebook.com/
    twitter: //twitter.com/
    google-plus: //plus.google.com/
    github: //github.com/
    stack-overflow: //stackoverflow.com/
    instagram: //instagram.com/
    pinterest: //pinterest.com/
    steam: //steamcommunity.com/
license: MIT License


# theme variables, change this to make site looks best.
baseurl: https://moviesplay9.github.io
paginate: 2


# system variables, do not change unless you knew what's it does.
paginate_path: page/:num
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
